In [1]:
import numpy as np
import random

In [2]:
# Создайте два одномерных массива из случайных целых чисел от 1 до 10.
arr_1 = np.random.randint(1, 11, 10)
arr_2 = np.random.randint(1, 11, 10)
print(f"""First one-dimensional array of random integers from 1 to 10:
    {arr_1}
Second one-dimensional array of random integers from 1 to 10:
    {arr_2}""")

First one-dimensional array of random integers from 1 to 10:
    [ 2 10  4  1  7  5  9  7  5  1]
Second one-dimensional array of random integers from 1 to 10:
    [9 7 5 2 9 4 6 3 4 9]


In [3]:
# Выполните поэлементное сложение этих двух массивов.
sum_arr = arr_1 + arr_2
print(f"Result of element-by-element addition of two arrays:\n\t{sum_arr}")

Result of element-by-element addition of two arrays:
	[11 17  9  3 16  9 15 10  9 10]


In [4]:
# Измените форму полученного массива на матрицу 2x5.
new_shape = sum_arr.reshape(2, 5)
print(f"The shape of the array BEFORE the change:\n\t{sum_arr.shape}")
print(f"Shape of the array AFTER the change:\n\t{new_shape.shape}")

The shape of the array BEFORE the change:
	(10,)
Shape of the array AFTER the change:
	(2, 5)


In [5]:
# Посчитайте среднее значение
print(f"The average of all elements of the array \n{new_shape} \nis equal: {np.mean(new_shape)}")

The average of all elements of the array 
[[11 17  9  3 16]
 [ 9 15 10  9 10]] 
is equal: 10.9


In [6]:
# Создайте массив размером 3x3 и выведите его первую строку и первый столбец.
arr_3 = np.random.randint(1, 11, size=(3, 3))
print(f"3x3 array is created:\n{arr_3}")
print(f"First row of the array:\n{arr_3[0]}")
print(f"First column of the array:\n{arr_3[:, 0]}")

3x3 array is created:
[[ 9  9  1]
 [ 5  6  7]
 [10  7  4]]
First row of the array:
[9 9 1]
First column of the array:
[ 9  5 10]


In [7]:
# Измените форму массива с помощью функции reshape и выведите его новую форму.
new_arr_3 = arr_3.reshape(9, 1)
print(f"The shape of the array BEFORE the change:\n\t{arr_3.shape}")
print(arr_3)
print(f"Shape of the array AFTER the change:\n\t{new_arr_3.shape}")
print(new_arr_3)

The shape of the array BEFORE the change:
	(3, 3)
[[ 9  9  1]
 [ 5  6  7]
 [10  7  4]]
Shape of the array AFTER the change:
	(9, 1)
[[ 9]
 [ 9]
 [ 1]
 [ 5]
 [ 6]
 [ 7]
 [10]
 [ 7]
 [ 4]]


In [8]:
# Используйте функцию flatten, чтобы преобразовать массив в одномерный.
print(f"The shape of the array BEFORE the change:\n\t{new_arr_3.shape}")
print(new_arr_3)
new_arr_3 = arr_3.flatten()
print(f"Shape of the array AFTER the change:\n\t{new_arr_3.shape}")
print(new_arr_3)

The shape of the array BEFORE the change:
	(9, 1)
[[ 9]
 [ 9]
 [ 1]
 [ 5]
 [ 6]
 [ 7]
 [10]
 [ 7]
 [ 4]]
Shape of the array AFTER the change:
	(9,)
[ 9  9  1  5  6  7 10  7  4]


In [9]:
# Создайте двумерный массив размером 4x3 с случайными целыми числами от 1 до 10.
arr_4 = np.random.randint(1, 11, (4, 3))
print(f"""Two-dimensional 4x3 array with random integers from 1 to 10:
{arr_4}""")

Two-dimensional 4x3 array with random integers from 1 to 10:
[[ 7 10  5]
 [ 8 10  3]
 [ 8  1  4]
 [ 7 10  2]]


In [11]:
# Объедините столбцы этого массива в один столбец с использованием vstack.
print(np.vstack(arr_4.flatten()))

[[ 7]
 [10]
 [ 5]
 [ 8]
 [10]
 [ 3]
 [ 8]
 [ 1]
 [ 4]
 [ 7]
 [10]
 [ 2]]


In [12]:
# Создайте массив из 9 случайных чисел от 1 до 30.
arr_5 = np.random.randint(1, 30, 9)
print(f"Array of 9 random numbers from 1 to 30: {arr_5}")

Array of 9 random numbers from 1 to 30: [ 5 12 14  3  4 11 14 28 21]


In [13]:
# Найдите индекс максимального значения в массиве и выведите это значение.
max_index = np.argmax(arr_5)
# Взял отсюда: https://numpy.org/doc/stable/reference/generated/numpy.argmax.html#numpy.argmax
print("Index of the maximum value in the array:", max_index)

Index of the maximum value in the array: 7


In [14]:
# Создайте два массива, каждый размером 2x2, состоящих из случайных целых чисел от 1 до 5.
arr_6 = np.random.randint(1, 5, (2, 2))
arr_7 = np.random.randint(1, 5, (2, 2))
print("First array\n", arr_6)
print("Second array\n", arr_7)

First array
 [[3 2]
 [4 3]]
Second array
 [[2 4]
 [2 4]]


In [15]:
# Транспонируйте один из массивов.
print("Transposed array\n", arr_6.T)

Transposed array
 [[3 4]
 [2 3]]


In [16]:
# Сложите транспонированный массив с другим массивом.
print("Sum of arrays\n", arr_6.T + arr_7)

Sum of arrays
 [[5 8]
 [4 7]]
